name: Déploiement Vite sur GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm  # Accélère les builds suivants

      - name: Installer les dépendances
        run: npm ci

      - name: Build du projet
        run: npm run build  # Génère le dossier /dist

      - name: Déployer l'artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist  # Chemin crucial

      - name: Déploiement
        uses: actions/deploy-pages@v4
